INSERT INTO candidatos (ID_ESTADO,ID_DISTRITO, NOMBRE_ESTADO, PARTIDO_CI, CANDIDATURA_PROPIETARIA, CANDIDATURA_SUPLENTE, CANDIDATO_A)VALUES(0,0,'ALL','PAN','RICARDO ANAYA CORTES
','-','Presidente');
INSERT INTO candidatos (ID_ESTADO,ID_DISTRITO, NOMBRE_ESTADO, PARTIDO_CI, CANDIDATURA_PROPIETARIA, CANDIDATURA_SUPLENTE, CANDIDATO_A)VALUES(0,0,'ALL','PRI','JOSÉ ANTONIO MEADE KURIBREÑA
','-','Presidente');
INSERT INTO candidatos (ID_ESTADO,ID_DISTRITO, NOMBRE_ESTADO, PARTIDO_CI, CANDIDATURA_PROPIETARIA, CANDIDATURA_SUPLENTE, CANDIDATO_A)VALUES(0,0,'ALL','PRD','RICARDO ANAYA CORTES
','-','Presidente');
INSERT INTO candidatos (ID_ESTADO,ID_DISTRITO, NOMBRE_ESTADO, PARTIDO_CI, CANDIDATURA_PROPIETARIA, CANDIDATURA_SUPLENTE, CANDIDATO_A)VALUES(0,0,'ALL','PVEM','JOSÉ ANTONIO MEADE KURIBREÑA
','-','Presidente');
INSERT INTO candidatos (ID_ESTADO,ID_DISTRITO, NOMBRE_ESTADO, PARTIDO_CI, CANDIDATURA_PROPIETARIA, CANDIDATURA_SUPLENTE, CANDIDATO_A)VALUES(0,0,'ALL','PT','ANDRÉS MANUEL LÓPEZ OBRADOR
','-','Presidente');
INSERT INTO candidatos (ID_ESTADO,ID_DISTRITO, NOMBRE_ESTADO, PARTIDO_CI, CANDIDATURA_PROPIETARIA, CANDIDATURA_SUPLENTE, CANDIDATO_A)VALUES(0,0,'ALL','MC','RICARDO ANAYA CORTES
','-','Presidente');
INSERT INTO candidatos (ID_ESTADO,ID_DISTRITO, NOMBRE_ESTADO, PARTIDO_CI, CANDIDATURA_PROPIETARIA, CANDIDATURA_SUPLENTE, CANDIDATO_A)VALUES(0,0,'ALL','NUEVA ALIANZA','JOSÉ ANTONIO MEADE KURIBREÑA
','-','Presidente');
INSERT INTO candidatos (ID_ESTADO,ID_DISTRITO, NOMBRE_ESTADO, PARTIDO_CI, CANDIDATURA_PROPIETARIA, CANDIDATURA_SUPLENTE, CANDIDATO_A)VALUES(0,0,'ALL','MORENA','ANDRÉS MANUEL LÓPEZ OBRADOR
','-','Presidente');
INSERT INTO candidatos (ID_ESTADO,ID_DISTRITO, NOMBRE_ESTADO, PARTIDO_CI, CANDIDATURA_PROPIETARIA, CANDIDATURA_SUPLENTE, CANDIDATO_A)VALUES(0,0,'ALL','PES','ANDRÉS MANUEL LÓPEZ OBRADOR
','-','Presidente');
INSERT INTO candidatos (ID_ESTADO,ID_DISTRITO, NOMBRE_ESTADO, PARTIDO_CI, CANDIDATURA_PROPIETARIA, CANDIDATURA_SUPLENTE, CANDIDATO_A)VALUES(0,0,'ALL','PAN_PRD_MC','RICARDO ANAYA CORTES
','-','Presidente');
INSERT INTO candidatos (ID_ESTADO,ID_DISTRITO, NOMBRE_ESTADO, PARTIDO_CI, CANDIDATURA_PROPIETARIA, CANDIDATURA_SUPLENTE, CANDIDATO_A)VALUES(0,0,'ALL','PAN_PRD','RICARDO ANAYA CORTES
','-','Presidente');
INSERT INTO candidatos (ID_ESTADO,ID_DISTRITO, NOMBRE_ESTADO, PARTIDO_CI, CANDIDATURA_PROPIETARIA, CANDIDATURA_SUPLENTE, CANDIDATO_A)VALUES(0,0,'ALL','PAN_MC','RICARDO ANAYA CORTES
','-','Presidente');
INSERT INTO candidatos (ID_ESTADO,ID_DISTRITO, NOMBRE_ESTADO, PARTIDO_CI, CANDIDATURA_PROPIETARIA, CANDIDATURA_SUPLENTE, CANDIDATO_A)VALUES(0,0,'ALL','PRD_MC','RICARDO ANAYA CORTES
','-','Presidente');
INSERT INTO candidatos (ID_ESTADO,ID_DISTRITO, NOMBRE_ESTADO, PARTIDO_CI, CANDIDATURA_PROPIETARIA, CANDIDATURA_SUPLENTE, CANDIDATO_A)VALUES(0,0,'ALL','PRI_PVEM_NA','JOSÉ ANTONIO MEADE KURIBREÑA
','-','Presidente');
INSERT INTO candidatos (ID_ESTADO,ID_DISTRITO, NOMBRE_ESTADO, PARTIDO_CI, CANDIDATURA_PROPIETARIA, CANDIDATURA_SUPLENTE, CANDIDATO_A)VALUES(0,0,'ALL','PRI_PVEM','JOSÉ ANTONIO MEADE KURIBREÑA
','-','Presidente');
INSERT INTO candidatos (ID_ESTADO,ID_DISTRITO, NOMBRE_ESTADO, PARTIDO_CI, CANDIDATURA_PROPIETARIA, CANDIDATURA_SUPLENTE, CANDIDATO_A)VALUES(0,0,'ALL','PRI_NA','JOSÉ ANTONIO MEADE KURIBREÑA
','-','Presidente');
INSERT INTO candidatos (ID_ESTADO,ID_DISTRITO, NOMBRE_ESTADO, PARTIDO_CI, CANDIDATURA_PROPIETARIA, CANDIDATURA_SUPLENTE, CANDIDATO_A)VALUES(0,0,'ALL','PVEM_NA','JOSÉ ANTONIO MEADE KURIBREÑA
','-','Presidente');
INSERT INTO candidatos (ID_ESTADO,ID_DISTRITO, NOMBRE_ESTADO, PARTIDO_CI, CANDIDATURA_PROPIETARIA, CANDIDATURA_SUPLENTE, CANDIDATO_A)VALUES(0,0,'ALL','PT_MORENA_PES','ANDRÉS MANUEL LÓPEZ OBRADOR
','-','Presidente');
INSERT INTO candidatos (ID_ESTADO,ID_DISTRITO, NOMBRE_ESTADO, PARTIDO_CI, CANDIDATURA_PROPIETARIA, CANDIDATURA_SUPLENTE, CANDIDATO_A)VALUES(0,0,'ALL','PT_MORENA','ANDRÉS MANUEL LÓPEZ OBRADOR
','-','Presidente');
INSERT INTO candidatos (ID_ESTADO,ID_DISTRITO, NOMBRE_ESTADO, PARTIDO_CI, CANDIDATURA_PROPIETARIA, CANDIDATURA_SUPLENTE, CANDIDATO_A)VALUES(0,0,'ALL','PT_PES','ANDRÉS MANUEL LÓPEZ OBRADOR
','-','Presidente');
INSERT INTO candidatos (ID_ESTADO,ID_DISTRITO, NOMBRE_ESTADO, PARTIDO_CI, CANDIDATURA_PROPIETARIA, CANDIDATURA_SUPLENTE, CANDIDATO_A)VALUES(0,0,'ALL','MORENA_PES','ANDRÉS MANUEL LÓPEZ OBRADOR
','-','Presidente');
INSERT INTO candidatos (ID_ESTADO,ID_DISTRITO, NOMBRE_ESTADO, PARTIDO_CI, CANDIDATURA_PROPIETARIA, CANDIDATURA_SUPLENTE, CANDIDATO_A)VALUES(0,0,'ALL','CI_39987','MARGARITA ESTER ZAVALA GÓMEZ DEL CAMPO
','-','Presidente');
INSERT INTO candidatos (ID_ESTADO,ID_DISTRITO, NOMBRE_ESTADO, PARTIDO_CI, CANDIDATURA_PROPIETARIA, CANDIDATURA_SUPLENTE, CANDIDATO_A)VALUES(0,0,'ALL','CI_76991','JAIME HELIODORO RODRIGUEZ CALDERON
','-','Presidente');
